"""empty message

Revision ID: 25e19b2d806c
Revises: 
Create Date: 2023-09-06 20:23:17.429539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e19b2d806c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('dept_name', sa.String(length=64), nullable=False),
    sa.CheckConstraint("dept_name IN ('Physics', 'M&S', 'CSSE')"),
    sa.PrimaryKeyConstraint('dept_id'),
    sa.UniqueConstraint('dept_name')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.CheckConstraint("role_name IN ('HoS', 'HoD', 'Staff', 'Admin')"),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('user',
    sa.Column('username', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('leave_hours', sa.Float(), nullable=True),
    sa.Column('contract_hour', sa.Float(), nullable=True),
    sa.Column('available_hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('work',
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('work_explanation', sa.String(length=128), nullable=False),
    sa.Column('work_type', sa.String(length=64), nullable=False),
    sa.Column('default_hours', sa.Float(), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("work_type IN ('ADMIN', 'CWS', 'GA', 'HDR', 'ORES', 'RES-MGMT', 'RESERV', 'SDS', 'TEACH', 'UDEV')"),
    sa.ForeignKeyConstraint(['dept_id'], ['department.dept_id'], ),
    sa.PrimaryKeyConstraint('work_id')
    )
    op.create_table('workload_allocation',
    sa.Column('alloc_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('hours_allocated', sa.Float(), nullable=True),
    sa.Column('username', sa.Integer(), nullable=True),
    sa.Column('approval_status', sa.String(length=64), nullable=True),
    sa.CheckConstraint("approval_status IN ('Approved', 'Pending')"),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.work_id'], ),
    sa.PrimaryKeyConstraint('alloc_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workload_allocation')
    op.drop_table('work')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('department')
    # ### end Alembic commands ###
