"""Add columns:work category,leave type,unitcode,workload point,staff dept

Revision ID: 4f831bd047cb
Revises: a41274e266d9
Create Date: 2023-09-15 11:53:08.212763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f831bd047cb'
down_revision = 'a41274e266d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('dept foreign key', 'department', ['dept_id'], ['dept_id'])

    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_code', sa.String(length=64), nullable=True))
        batch_op.alter_column('work_explanation',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('dept_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('workload_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workload_point', sa.Float(), nullable=False))
        batch_op.alter_column('work_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hours_allocated',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workload_allocation', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hours_allocated',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('work_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('workload_point')

    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.alter_column('dept_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('work_explanation',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('unit_code')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('foreignkey', type_='foreignkey')
        batch_op.drop_column('dept_id')

    # ### end Alembic commands ###
