# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.expected_conditions import visibility_of_element_located

class TestStaff():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_staff(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1549, 955)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("33333333")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("staffpassword")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Assign Workload").click()

    WebDriverWait(self.driver, 3).until(visibility_of_element_located((By.CSS_SELECTOR, ".flash-message")))
    flash_message = self.driver.find_element(By.CSS_SELECTOR, ".flash-message").text
    assert "You do not have permission to access this page." in flash_message, f"Expected 'Expected Text' but got {flash_message}"

    assert self.driver.current_url == "http://127.0.0.1:5000/dashboard", f"Expected 'http://127.0.0.1:5000/dashboard' but got {self.driver.current_url}"
    print("Access denied successfully")
    
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
if __name__ == "__main__":
    test = TestStaff()
    test.setup_method(None)

    try:
        test.test_staff()
        print("Test passed successfully")
    except Exception as e:
        print("Test failed", e)
    finally:
        test.teardown_method(None)